services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/jsons:/data
      - mongodb_data:/data/db

  rest-api:
    build:
      context: ./RestAPI
      dockerfile: Dockerfile
    container_name: rest-api
    depends_on:
      - mongodb
    links:
      - mongodb

  web-server:
    build:
      context: ./Mappa
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - "3067:3067"
    depends_on:
      - rest-api
      - mongodb
    links:
      - rest-api

volumes:
  mongodb_data: