services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data:/data/db
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-api
    ports:
      - "3000:1502"
    depends_on:
      - mongodb
    links:
      - mongodb
        